---
    name: CI
    
    "on":
      push:
        branches: [main,master,develop]
      pull_request:
        branches: [main,master,develop]
      workflow_dispatch:
    
    jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.11"
    
          - name: Install Graphviz
            uses: ts-graphviz/setup-graphviz@v2
    
          - name: Install deps (best-effort)
            run: |
              python -m pip install --upgrade pip
              if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then
                pip install .
              else
                echo "No Python packaging config; skipping 'pip install .'"
              fi
    
          - name: Run tests (best-effort)
            run: |
              if [ -d tests ]; then
                pip install pytest
                pytest -q
              else
                echo "No tests directory; skipping pytest."
              fi
    
          - name: Optional: render examples (best-effort)
            run: |
              if [ -d examples ]; then
                mkdir -p out
                echo "Renderer not implemented yet; skipping."
              else
                echo "No examples directory; skipping."
              fi
    